In [42]:
import pandas as pd
import numpy as np

DATA_ROOT = "../data/mfeat/"
X_i = {"mfeat-" + x: None for x in ["fou", "fac", "kar", "mor", "pix", "zer"]}

## Description for data

FOU: 76 features

FAC: 216 features

KAR: 64 features

PIX: 240 features

ZER: 47 features

MOR: 6 features

In [43]:
for k, _ in X_i.items():
    X_i[k] = pd.read_csv(DATA_ROOT + k, header=None, delim_whitespace=True)
    print(f"Original -> {k}: {X_i[k].shape}")

Original -> mfeat-fou: (2000, 76)
Original -> mfeat-fac: (2000, 216)
Original -> mfeat-kar: (2000, 64)
Original -> mfeat-mor: (2000, 6)
Original -> mfeat-pix: (2000, 240)
Original -> mfeat-zer: (2000, 47)


In [45]:
# label set is sequential of elements from 0 to 9 each with 200
label = np.repeat(range(10), 200)
print(label.shape)
label

(2000,)


array([0, 0, 0, ..., 9, 9, 9])

In [48]:
temp = np.random.rand(4, 3)
temp

array([[0.15916808, 0.3963739 , 0.00758583],
       [0.03237285, 0.0629466 , 0.19749315],
       [0.95291415, 0.01735836, 0.51374343],
       [0.81394316, 0.92583546, 0.12431873]])

In [49]:
np.linalg.norm(temp, axis=1)

array([0.42720521, 0.20979471, 1.08271834, 1.2390036 ])